FROM python:3.7.5

WORKDIR /opt/app

RUN pip install pipenv

COPY Pipfile /opt/app
COPY Pipfile.lock /opt/app

RUN pipenv sync

COPY . /opt/app

RUN pipenv run nuitka3 --lto main.py --recurse-all --standalone --remove-output

CMD ["./main.dist/main", "console"]
